apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp
  labels: 
    app: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        env:
          - name: WORDPRESS_DB_USER
            value: wordpress
          - name: WORDPRESS_DB_PASSWORD
            value: root
          - name: WORDPRESS_DB_HOST
            value: mysql
        ports:
            - containerPort: 80
    

    
       


  
