apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  containers:
  - name: busybox
    image: busybox:latest
    args:
      - sleep
      - "1000"
    env:
    - name: SPECIAL_LEVEL_KEY
      valueFrom:
        configMapKeyRef:
          name: cm-busybox
          key: greeting
    command:
    - /bin/sh
    - -c
    - "cat /opt/app/message/greeting && sleep 5"  
      
    volumeMounts:
    - name: config-volume
      mountPath: /opt/app/message

  volumes:
  - name: config-volume
    configMap:
      name: cm-busybox
  restartPolicy: Never