apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
kind: Service
apiVersion: v1
metadata:
  name: mysql-nodeport
spec:
  type: NodePort
  selector:
     app: mysql
  ports:
    - protocol: TCP
      port: 3308
      targetPort: 3306
      nodePort: 30089
